version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
    groups:
      cargo-minor-patch:
        update-types: [minor, patch]
  - package-ecosystem: npm
    directory: "/interface"
    schedule:
      interval: weekly
    groups:
      interface-minor-patch:
        update-types: [minor, patch]
  - package-ecosystem: npm
    directory: "/desktop"
    schedule:
      interval: weekly
    groups:
      desktop-minor-patch:
        update-types: [minor, patch]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
