/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe: confirms the process is up AND the database answers a
         *     trivial query, so orchestrators stop routing traffic to an instance whose
         *     database is gone (returns 503). A liveness-only check would report healthy
         *     with a dead database and keep receiving requests.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_categories"];
        put?: never;
        post: operations["create_category"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_category"];
        put: operations["update_category"];
        post?: never;
        delete: operations["delete_category"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_expenses"];
        put?: never;
        post: operations["create_expense"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/expenses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_expense"];
        put: operations["update_expense"];
        post?: never;
        delete: operations["delete_expense"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_settings"];
        put: operations["update_settings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Category: {
            color: string;
            /** Format: date-time */
            created_at: string;
            id: string;
            /**
             * Format: int64
             * @description Optional monthly budget in integer minor units (cents). `None` = no budget.
             */
            monthly_budget_cents?: number | null;
            name: string;
        };
        CategorySpend: {
            /**
             * Format: int64
             * @description Monthly budget in cents, when the category sets one.
             */
            budget_cents?: number | null;
            /** @description `None` for the synthetic "Uncategorized" bucket. */
            category_id?: string | null;
            color: string;
            name: string;
            /** Format: int64 */
            spent_cents: number;
        };
        CreateCategory: {
            /** @description Hex color like `#6366f1`. Defaults to a neutral indigo when omitted. */
            color?: string;
            /** Format: int64 */
            monthly_budget_cents?: number | null;
            name: string;
        };
        CreateExpense: {
            /** Format: int64 */
            amount_cents: number;
            category_id?: string | null;
            description?: string;
            spent_on: string;
        };
        Expense: {
            /**
             * Format: int64
             * @description Amount in integer minor units (cents). Always positive.
             */
            amount_cents: number;
            category_id?: string | null;
            /**
             * @description Denormalized category name (via LEFT JOIN) for display; `None` when
             *     uncategorized or the category was deleted.
             */
            category_name?: string | null;
            /** Format: date-time */
            created_at: string;
            description: string;
            id: string;
            /** @description Calendar date the money was spent, `YYYY-MM-DD`. */
            spent_on: string;
        };
        Health: {
            /** @description "ok" when a trivial query against the database succeeds, else "unreachable". */
            database: string;
            /** @description "ok" when the service and its database are reachable, else "degraded". */
            status: string;
            version: string;
        };
        MonthSummary: {
            /**
             * @description Per-category spend for the month: every category that was spent on or
             *     that sets a budget, plus an "Uncategorized" bucket when relevant.
             */
            categories: components["schemas"]["CategorySpend"][];
            /** @description The month this summary covers, `YYYY-MM`. */
            month: string;
            /** @description Totals for up to the last 6 months ending at `month`, oldest first. */
            recent_months: components["schemas"]["MonthTotal"][];
            /** Format: int64 */
            total_cents: number;
        };
        MonthTotal: {
            /** @description `YYYY-MM`. */
            month: string;
            /** Format: int64 */
            total_cents: number;
        };
        Settings: {
            /** @description ISO 4217-style 3-letter currency code, e.g. "USD", "EUR". */
            base_currency: string;
        };
        UpdateCategory: {
            color: string;
            /** Format: int64 */
            monthly_budget_cents?: number | null;
            name: string;
        };
        UpdateExpense: {
            /** Format: int64 */
            amount_cents: number;
            category_id?: string | null;
            description?: string;
            spent_on: string;
        };
        UpdateSettings: {
            base_currency: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service and database are healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Database is unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    list_categories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All categories, A–Z */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
        };
    };
    create_category: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategory"];
            };
        };
        responses: {
            /** @description Category created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            /** @description Invalid name or budget */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_category: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Category id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The category */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            /** @description Unknown id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_category: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Category id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCategory"];
            };
        };
        responses: {
            /** @description Updated category */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            /** @description Invalid name or budget */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_category: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Category id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Category deleted; its expenses are uncategorized */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_expenses: {
        parameters: {
            query?: {
                /** @description Filter to a single month, `YYYY-MM`. */
                month?: string | null;
                /** @description Filter to a single category id. */
                category_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Expenses, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Expense"][];
                };
            };
            /** @description Malformed month filter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_expense: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExpense"];
            };
        };
        responses: {
            /** @description Expense created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Expense"];
                };
            };
            /** @description Invalid amount, date, or category */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_expense: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Expense id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The expense */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Expense"];
                };
            };
            /** @description Unknown id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_expense: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Expense id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateExpense"];
            };
        };
        responses: {
            /** @description Updated expense */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Expense"];
                };
            };
            /** @description Invalid amount, date, or category */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_expense: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Expense id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Expense deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
        };
    };
    update_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSettings"];
            };
        };
        responses: {
            /** @description Updated settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            /** @description Invalid currency code */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_summary: {
        parameters: {
            query?: {
                /** @description Month to summarize, `YYYY-MM`. Defaults to the current UTC month. */
                month?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Spending summary for the month */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthSummary"];
                };
            };
            /** @description Malformed month */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
